/**
 * AUTOGENERATED by `pnpm bones:build` (boneyard-js). Do NOT hand-edit.
 *
 * Placeholder until the first capture. `bones:build` visits the running app
 * (incl. /dev/bones), snapshots every named <Skeleton>, and overwrites this
 * file with captured bone data keyed by name. Commit the regenerated file plus
 * any `*.bones.json` it emits (CLAUDE.md § Project Conventions · Boneyard).
 */
import type { ResponsiveBones, SkeletonResult } from "boneyard-js";

export const registry: Record<string, SkeletonResult | ResponsiveBones> = {};
